### ISSUE TITLE
Problems to pre define values for a weekline

### ISSUE THREAD

**Issue by knubew** [dkLtd/weekLine#1]
Hi,

I have problems to pre define values for a weekline. I can't get it work. Probably I'm too stupid, because I can't see, what I'm doing wrong. Any help would be appreciated.

I use the following sample code for an "test.html" file that is placed in the "weekLine-master" folder: 

```
<html>
<head>
<link rel="Stylesheet" href="styles/cleanslate.css" />
<link rel="Stylesheet" href="styles/jquery.weekLine-white.css" />
<script src="http://code.jquery.com/jquery-latest.min.js"></script>
<script src="scripts/jquery.weekLine.js"></script>
<script>
$(document).ready(function(){
    // Return selected days as dates,
    // starting from coming Monday
    var weekCal = $("#weekCal").weekLine({
        dayLabels: ["So.", "Mo.", "Di.", "Mi.", "Do.", "Fr.", "Sa."],
        onChange: function () {
            $('#selectedDays').html($(this).weekLine('getSelected', 'indexes'));
            $('#selectedDaysInput').val($(this).weekLine('getSelected', 'indexes'));
        }
    });
    // Pre select some days
    weekCal.weekLine("setSelected", "2,3,4"); 
});
</script>

<title>jQuery Days-Of-Week-Picker Plugin</title>
</head>
<body>
<h1 style="margin-top:150px;"></h1>
<table border="1">
<tr>
    <td height="25">
        <div class="weekDays" id="weekCal"></div>
    </td>
</tr>
<tr>
    <td height="25">
        <div id="selectedDays"></div>
    </td>
</tr>
<tr>
    <td height="25">
        <input id="selectedDaysInput" type="text" />
    </td>
</tr>
</table>
</body>
</html>
```

**Comment by dkLtd** [comment]
Your test.html seems perfectly fine and it actually works on my side. Are you sure you have the correct paths for the hrefs and the src?

If are set properly, then check for javascript errors, which will give us a clue for what went wrong. What browser you use? If you use firefox, use firebug (https://getfirebug.com/firstrun#Firebug%202.0.7) for debugging.

**Comment by knubew** [comment]
Thanks for your response. I used firebug and found out, that it works with jQuery 1.7.2 but NOT with any higher jQuery version. See the attached screenshot, please. I would be nice if you could fix this problem, because I need to use a higher jQuery version in my site.
![weekline_jquery-error](https://cloud.githubusercontent.com/assets/6688340/5597111/fdc21e84-929c-11e4-9948-f6f90914ae32.jpg)

**Comment by dkLtd** [comment]
that info helped

I managed to reproduce it and therefore, will fix it shortly

**Comment by knubew** [comment]
thanks. fixing would bie nice.

**Comment by dkLtd** [comment]
I don't have the repo in this pc, in order to upload quickly the fix. So, if you don't want to wait, just replace "a:[href='#" with "a[href='#" and you will be fine.

Will upload a new version shortly (over the weekend) with few additional features anyway.

**Comment by knubew** [comment]
Thank you very much, but I can wait until you updated the repo.

**Comment by dkLtd** [comment]
Just pushed a new version. Please, tell me if it is working now.

I am already using the new version in http://codebits.weebly.com/game-scheduler.html. You can find the js file for that example use here: http://codebits.weebly.com/files/theme/league-negotiator.js.

**Comment by knubew** [comment]
OK, thanks. I will also test the new version.

**Comment by knubew** [comment]
```
Just pushed a new version. Please, tell me if it is working now.
```

Thank you. Everthing is fine. You can close this issue.
