### ISSUE TITLE
Monday as the first day of week

### ISSUE THREAD

**Issue by knubew** [dkLtd/weekLine#2]
I'v tried to set Monday for the first day of week (Mon=0 ... Sun=6), but it fails. It seems that there is no "nextMonday()" function, but you wrote in your examples (startDate: nextMonday()).
![missing_function_nextmonday](https://cloud.githubusercontent.com/assets/6688340/5603469/01edd940-9387-11e4-9072-b5b39663644b.jpg)

**Comment by dkLtd** [comment]
use nextDay(0)

I don't know if you are familiar with javascript, jquery and jquery plugins, but do not be afraid to open the js plugin file from the plugins you use. They usually contain straight forward info, which sometimes isn’t included in the readme/help files, like all the options you can use. In this case you need the function at the end:

``` javascript
// Helper function for getting the next week day
// Monday (0) to Sunday (6)
function nextDay(dayNum) {
    return function(date) {
        var dt = new Date(date || new Date());
        return new Date(dt.getTime() + ((dayNum - dt.getDay() + 7) % 7 + 1) * 86400000);
    };
}   
```
