### ISSUE TITLE
Altering values for days

### ISSUE THREAD

**Issue by knubew** [dkLtd/weekLine#3]
Is it possible to integrate a paramter "weekStart:" (similar to "dayLabels:")  to alter the values for the single days ?

In my database with more than 100.000 datasets I use these values:
 1=Sunday - 2=Monday - 3=Tuesday - 4=Wednesday - 5=Thursday - 6=Friday - 7=Saturday

**Comment by dkLtd** [comment]
if I understand correctly, you can simple +1
